"""Curated emoji catalog, grouped like the Windows emoji panel."""

EMOJI: dict[str, list[tuple[str, str]]] = {
    "Smileys": [
        ("😀", "grinning face"),
        ("😃", "grinning face big eyes"),
        ("😄", "grinning face smiling eyes"),
        ("😁", "beaming face"),
        ("😆", "grinning squinting laughing"),
        ("😅", "grinning sweat"),
        ("🤣", "rolling on the floor laughing"),
        ("😂", "tears of joy"),
        ("🙂", "slightly smiling"),
        ("😉", "winking face"),
        ("😊", "smiling face blush"),
        ("😇", "smiling halo innocent"),
        ("🥰", "smiling with hearts love"),
        ("😍", "heart eyes love"),
        ("🤩", "star struck"),
        ("😘", "face blowing kiss"),
        ("😋", "yummy face savoring"),
        ("😜", "winking tongue"),
        ("🤪", "zany face crazy"),
        ("🤔", "thinking face"),
        ("🤨", "raised eyebrow suspicious"),
        ("😐", "neutral face"),
        ("😏", "smirking face"),
        ("😒", "unamused face"),
        ("🙄", "rolling eyes"),
        ("😬", "grimacing face awkward"),
        ("😌", "relieved face"),
        ("😴", "sleeping face"),
        ("🤒", "sick thermometer"),
        ("🤯", "exploding head mind blown"),
        ("🥳", "partying face celebration"),
        ("😎", "sunglasses cool"),
        ("🤓", "nerd face glasses"),
        ("😕", "confused face"),
        ("😟", "worried face"),
        ("😢", "crying face sad"),
        ("😭", "loudly crying sobbing"),
        ("😤", "steam from nose frustrated"),
        ("😠", "angry face"),
        ("😡", "pouting face rage"),
        ("🤬", "cursing swearing"),
        ("😱", "screaming in fear"),
        ("😳", "flushed face embarrassed"),
        ("🥺", "pleading face puppy eyes"),
        ("😈", "smiling devil horns"),
        ("💀", "skull dead"),
        ("🤡", "clown face"),
        ("👻", "ghost"),
        ("🤖", "robot"),
        ("💩", "pile of poo"),
    ],
    "Gestures & People": [
        ("👍", "thumbs up"),
        ("👎", "thumbs down"),
        ("👌", "ok hand"),
        ("✌️", "victory peace"),
        ("🤞", "crossed fingers luck"),
        ("🤟", "love you gesture"),
        ("🤘", "sign of horns rock"),
        ("🤙", "call me hand"),
        ("👈", "pointing left"),
        ("👉", "pointing right"),
        ("👆", "pointing up"),
        ("👇", "pointing down"),
        ("☝️", "index up"),
        ("✋", "raised hand stop"),
        ("🖐️", "hand fingers splayed"),
        ("🖖", "vulcan salute"),
        ("👋", "waving hand hello bye"),
        ("🤚", "raised back of hand"),
        ("💪", "flexed biceps strong"),
        ("🙏", "folded hands please thanks"),
        ("👏", "clapping hands"),
        ("🙌", "raising hands celebration"),
        ("🤝", "handshake deal"),
        ("✍️", "writing hand"),
        ("🤦", "facepalm"),
        ("🤷", "shrug"),
        ("🙋", "raising hand"),
        ("🧠", "brain"),
        ("👀", "eyes looking"),
        ("👁️", "eye"),
        ("👂", "ear"),
        ("🗣️", "speaking head"),
        ("👶", "baby"),
        ("🧑", "person"),
        ("👨‍💻", "man technologist developer"),
        ("👩‍💻", "woman technologist developer"),
        ("🦸", "superhero"),
        ("🚶", "person walking"),
        ("🏃", "person running"),
        ("💃", "woman dancing"),
    ],
    "Animals & Nature": [
        ("🐶", "dog face"),
        ("🐱", "cat face"),
        ("🐭", "mouse face"),
        ("🐹", "hamster"),
        ("🐰", "rabbit bunny"),
        ("🦊", "fox"),
        ("🐻", "bear"),
        ("🐼", "panda"),
        ("🐨", "koala"),
        ("🐯", "tiger face"),
        ("🦁", "lion"),
        ("🐮", "cow face"),
        ("🐷", "pig face"),
        ("🐸", "frog"),
        ("🐵", "monkey face"),
        ("🐔", "chicken"),
        ("🐧", "penguin"),
        ("🐦", "bird"),
        ("🦆", "duck"),
        ("🦅", "eagle"),
        ("🦉", "owl"),
        ("🐺", "wolf"),
        ("🐴", "horse face"),
        ("🦄", "unicorn"),
        ("🐝", "bee"),
        ("🐛", "bug caterpillar"),
        ("🦋", "butterfly"),
        ("🐌", "snail"),
        ("🐢", "turtle"),
        ("🐍", "snake python"),
        ("🦖", "t-rex dinosaur"),
        ("🐙", "octopus"),
        ("🦀", "crab rust"),
        ("🐠", "tropical fish"),
        ("🐬", "dolphin"),
        ("🐳", "whale docker"),
        ("🌵", "cactus"),
        ("🌲", "evergreen tree"),
        ("🍀", "four leaf clover luck"),
        ("🌸", "cherry blossom"),
        ("🌹", "rose"),
        ("🌻", "sunflower"),
        ("🌙", "crescent moon"),
        ("⭐", "star"),
        ("🌟", "glowing star"),
        ("⚡", "lightning zap"),
        ("🔥", "fire hot"),
        ("🌈", "rainbow"),
        ("☀️", "sun"),
        ("☁️", "cloud"),
        ("❄️", "snowflake"),
        ("💧", "droplet water"),
        ("🌊", "wave ocean"),
    ],
    "Food & Drink": [
        ("🍎", "red apple"),
        ("🍌", "banana"),
        ("🍇", "grapes"),
        ("🍓", "strawberry"),
        ("🍉", "watermelon"),
        ("🍑", "peach"),
        ("🥭", "mango"),
        ("🍍", "pineapple"),
        ("🥥", "coconut"),
        ("🥑", "avocado"),
        ("🍅", "tomato"),
        ("🌶️", "hot pepper spicy"),
        ("🌽", "corn"),
        ("🥔", "potato"),
        ("🍞", "bread"),
        ("🥐", "croissant"),
        ("🧀", "cheese"),
        ("🍳", "cooking egg"),
        ("🥓", "bacon"),
        ("🍔", "hamburger"),
        ("🍟", "french fries"),
        ("🍕", "pizza"),
        ("🌭", "hot dog"),
        ("🌮", "taco"),
        ("🌯", "burrito"),
        ("🍜", "noodles ramen"),
        ("🍣", "sushi"),
        ("🍤", "fried shrimp"),
        ("🍚", "cooked rice"),
        ("🍦", "ice cream"),
        ("🍩", "doughnut"),
        ("🍪", "cookie"),
        ("🎂", "birthday cake"),
        ("🍫", "chocolate"),
        ("🍿", "popcorn"),
        ("☕", "coffee hot beverage"),
        ("🍵", "tea"),
        ("🥤", "cup with straw"),
        ("🍺", "beer"),
        ("🍷", "wine"),
        ("🥂", "clinking glasses cheers"),
    ],
    "Activities & Travel": [
        ("⚽", "soccer football"),
        ("🏀", "basketball"),
        ("🏈", "american football"),
        ("⚾", "baseball"),
        ("🎾", "tennis"),
        ("🏐", "volleyball"),
        ("🎱", "pool 8 ball"),
        ("🏓", "ping pong"),
        ("🏸", "badminton"),
        ("🥊", "boxing glove"),
        ("🏆", "trophy winner"),
        ("🥇", "gold medal first"),
        ("🎯", "bullseye target"),
        ("🎮", "video game controller"),
        ("🎲", "game die dice"),
        ("🧩", "puzzle piece"),
        ("♟️", "chess pawn"),
        ("🎳", "bowling"),
        ("🎤", "microphone"),
        ("🎧", "headphone"),
        ("🎸", "guitar"),
        ("🎹", "piano keyboard"),
        ("🥁", "drum"),
        ("🎨", "artist palette"),
        ("🎬", "clapper board movie"),
        ("🎪", "circus tent"),
        ("🚗", "car"),
        ("🚕", "taxi"),
        ("🚌", "bus"),
        ("🏎️", "racing car"),
        ("🚓", "police car"),
        ("🚑", "ambulance"),
        ("🚲", "bicycle"),
        ("🛵", "motor scooter"),
        ("🚂", "locomotive train"),
        ("✈️", "airplane"),
        ("🚀", "rocket ship launch"),
        ("🛸", "flying saucer ufo"),
        ("🚁", "helicopter"),
        ("⛵", "sailboat"),
        ("🚢", "ship"),
        ("🗺️", "world map"),
        ("🏔️", "mountain"),
        ("🏖️", "beach"),
        ("🏕️", "camping"),
        ("🗽", "statue of liberty"),
        ("🗼", "tokyo tower"),
        ("🏰", "castle"),
    ],
    "Objects & Tech": [
        ("💻", "laptop computer"),
        ("🖥️", "desktop computer"),
        ("⌨️", "keyboard"),
        ("🖱️", "computer mouse"),
        ("🖨️", "printer"),
        ("📱", "mobile phone"),
        ("☎️", "telephone"),
        ("🔋", "battery"),
        ("🔌", "electric plug"),
        ("💡", "light bulb idea"),
        ("🔦", "flashlight"),
        ("📷", "camera"),
        ("🎥", "movie camera"),
        ("📺", "television"),
        ("📻", "radio"),
        ("⏰", "alarm clock"),
        ("⌛", "hourglass"),
        ("📡", "satellite antenna"),
        ("🔍", "magnifying glass search"),
        ("🔒", "locked"),
        ("🔓", "unlocked"),
        ("🔑", "key"),
        ("🔨", "hammer"),
        ("🛠️", "hammer and wrench tools"),
        ("🔧", "wrench"),
        ("⚙️", "gear settings"),
        ("🧲", "magnet"),
        ("🧪", "test tube experiment"),
        ("🔬", "microscope"),
        ("🔭", "telescope"),
        ("💊", "pill medicine"),
        ("💉", "syringe"),
        ("🧯", "fire extinguisher"),
        ("🛒", "shopping cart"),
        ("🎁", "gift present"),
        ("🎈", "balloon"),
        ("🎉", "party popper tada"),
        ("🎊", "confetti ball"),
        ("✉️", "envelope email"),
        ("📦", "package box"),
        ("📌", "pushpin pin"),
        ("📎", "paperclip"),
        ("✂️", "scissors"),
        ("📝", "memo note"),
        ("📚", "books"),
        ("📖", "open book"),
        ("🗞️", "newspaper"),
        ("📈", "chart increasing growth"),
        ("📉", "chart decreasing"),
        ("📊", "bar chart"),
        ("💰", "money bag"),
        ("💵", "dollar banknote"),
        ("💳", "credit card"),
        ("🪙", "coin"),
    ],
    "Hearts & Symbols": [
        ("❤️", "red heart love"),
        ("🧡", "orange heart"),
        ("💛", "yellow heart"),
        ("💚", "green heart"),
        ("💙", "blue heart"),
        ("💜", "purple heart"),
        ("🖤", "black heart"),
        ("🤍", "white heart"),
        ("💔", "broken heart"),
        ("❣️", "heart exclamation"),
        ("💕", "two hearts"),
        ("💞", "revolving hearts"),
        ("💗", "growing heart"),
        ("💖", "sparkling heart"),
        ("💘", "heart with arrow"),
        ("💯", "hundred points"),
        ("💢", "anger symbol"),
        ("💥", "collision boom"),
        ("💫", "dizzy"),
        ("💦", "sweat droplets"),
        ("💤", "zzz sleep"),
        ("✨", "sparkles"),
        ("✅", "check mark button done"),
        ("❌", "cross mark no"),
        ("❓", "question mark"),
        ("❗", "exclamation mark"),
        ("⚠️", "warning"),
        ("🚫", "prohibited"),
        ("♻️", "recycling"),
        ("🔴", "red circle"),
        ("🟢", "green circle"),
        ("🟡", "yellow circle"),
        ("🔵", "blue circle"),
        ("🏁", "chequered flag finish"),
        ("🚩", "red flag"),
        ("🎌", "crossed flags"),
    ],
}
