"""Kaomoji (text faces), grouped like the Windows kaomoji panel."""

KAOMOJI: dict[str, list[tuple[str, str]]] = {
    "Happy": [
        ("(^‿^)", "smile happy"),
        ("(◕‿◕)", "cute smile"),
        ("(＾▽＾)", "big smile laugh"),
        ("(≧◡≦)", "joyful"),
        ("(ᵔᴥᵔ)", "happy bear"),
        ("(￣▽￣)", "content smug"),
        ("(๑˃ᴗ˂)ﻭ", "excited cheer"),
        ("(ノ^_^)ノ", "yay hands up"),
        ("ヽ(・∀・)ﾉ", "woohoo celebrate"),
        ("(☆▽☆)", "starry eyes"),
        ("＼(^o^)／", "hooray"),
        ("(o˘◡˘o)", "warm smile"),
    ],
    "Love": [
        ("(♡°▽°♡)", "in love"),
        ("(´♡‿♡`)", "love eyes"),
        ("(￣ε￣＠)", "kiss"),
        ("(っ˘з(˘⌣˘ )", "hug kiss couple"),
        ("(⊃｡•́‿•̀｡)⊃", "want hug"),
        ("(つ≧▽≦)つ", "hug"),
        ("(♥ω♥*)", "heart eyes"),
        ("(*^^*)", "blush shy"),
        ("(///▽///)", "blushing hard"),
    ],
    "Sad & Upset": [
        ("(╥﹏╥)", "crying"),
        ("(T_T)", "tears sad"),
        ("(;´д`)", "sigh distressed"),
        ("(っ˘̩╭╮˘̩)っ", "sad hug"),
        ("(´；ω；`)", "sobbing"),
        ("(◞‸◟)", "dejected"),
        ("(¬_¬)", "unimpressed side eye"),
        ("(－‸ლ)", "facepalm"),
        ("(￢з￢)", "annoyed smug"),
        ("(＃`Д´)", "angry"),
        ("(╬ Ò﹏Ó)", "furious"),
        ("(￣ヘ￣)", "hmph displeased"),
    ],
    "Actions & Classics": [
        ("¯\\_(ツ)_/¯", "shrug"),
        ("(╯°□°)╯︵ ┻━┻", "table flip rage"),
        ("┬─┬ノ( º _ ºノ)", "table unflip put back"),
        ("ᕕ( ᐛ )ᕗ", "strut happy walk"),
        ("(ง'̀-'́)ง", "fight ready"),
        ("(⌐■_■)", "deal with it sunglasses"),
        ("( ͡° ͜ʖ ͡°)", "lenny face"),
        ("(☞ﾟヮﾟ)☞", "finger guns"),
        ("(¬‿¬)", "smirk wink"),
        ("(°ロ°) !", "shocked surprised"),
        ("(⊙_⊙)", "wide eyes stare"),
        ("Σ(°△°|||)", "shocked panic"),
        ("(￣o￣) zzZ", "sleepy zzz"),
        ("( ˘ω˘ )ｽﾔｧ", "sleeping peaceful"),
        ("(≖ᴗ≖✿)", "smug satisfied"),
        ("(∪.∪ )...zzz", "napping"),
        ("ε=┌(;￣▽￣)┘", "running away"),
        ("(ノಠ益ಠ)ノ彡┻━┻", "angry table flip"),
        ("♪┏(・o･)┛♪", "dancing music"),
    ],
    "Animals": [
        ("(=^･ω･^=)", "cat"),
        ("(=^‥^=)", "cat face"),
        ("(U・x・U)", "bunny rabbit"),
        ("(・Θ・)", "bird"),
        ("V(=^･ω･^=)v", "cat peace"),
        ("ʕ•ᴥ•ʔ", "bear"),
        ("ʕ￫ᴥ￩ʔ", "bear side eye"),
        ("(￣(ｴ)￣)", "bear face"),
        ("(°)#))<<", "fish"),
        ("<コ:彡", "squid"),
    ],
}
