"""Symbol catalog, grouped like the Windows symbols panel."""

SYMBOLS: dict[str, list[tuple[str, str]]] = {
    "Punctuation & Typography": [
        ("—", "em dash"),
        ("–", "en dash"),
        ("…", "ellipsis"),
        ("«", "left guillemet"),
        ("»", "right guillemet"),
        ("‘", "left single quote"),
        ("’", "right single quote"),
        ("“", "left double quote"),
        ("”", "right double quote"),
        ("„", "low double quote"),
        ("†", "dagger"),
        ("‡", "double dagger"),
        ("•", "bullet"),
        ("◦", "white bullet"),
        ("‣", "triangle bullet"),
        ("§", "section sign"),
        ("¶", "pilcrow paragraph"),
        ("¡", "inverted exclamation"),
        ("¿", "inverted question"),
        ("‰", "per mille"),
        ("′", "prime minutes feet"),
        ("″", "double prime seconds inches"),
    ],
    "Currency": [
        ("€", "euro"),
        ("£", "pound sterling"),
        ("¥", "yen yuan"),
        ("₹", "indian rupee"),
        ("₩", "won"),
        ("₽", "ruble"),
        ("₺", "lira"),
        ("₫", "dong"),
        ("₪", "shekel"),
        ("¢", "cent"),
        ("₿", "bitcoin"),
        ("¤", "generic currency"),
    ],
    "Math": [
        ("±", "plus minus"),
        ("×", "multiplication"),
        ("÷", "division"),
        ("≈", "approximately equal"),
        ("≠", "not equal"),
        ("≡", "identical"),
        ("≤", "less than or equal"),
        ("≥", "greater than or equal"),
        ("∞", "infinity"),
        ("∑", "summation sigma"),
        ("∏", "product pi"),
        ("√", "square root"),
        ("∫", "integral"),
        ("∂", "partial derivative"),
        ("∆", "delta increment"),
        ("∇", "nabla gradient"),
        ("∈", "element of"),
        ("∉", "not element of"),
        ("∩", "intersection"),
        ("∪", "union"),
        ("⊂", "subset"),
        ("⊆", "subset or equal"),
        ("∅", "empty set"),
        ("∀", "for all"),
        ("∃", "there exists"),
        ("¬", "logical not"),
        ("∧", "logical and"),
        ("∨", "logical or"),
        ("⊕", "xor circled plus"),
        ("°", "degree"),
        ("µ", "micro mu"),
        ("½", "one half"),
        ("⅓", "one third"),
        ("¼", "one quarter"),
        ("¾", "three quarters"),
        ("²", "superscript two squared"),
        ("³", "superscript three cubed"),
        ("ⁿ", "superscript n"),
    ],
    "Arrows": [
        ("←", "left arrow"),
        ("→", "right arrow"),
        ("↑", "up arrow"),
        ("↓", "down arrow"),
        ("↔", "left right arrow"),
        ("↕", "up down arrow"),
        ("⇐", "double left arrow"),
        ("⇒", "double right arrow implies"),
        ("⇔", "double both arrow iff"),
        ("↩", "return left hook"),
        ("↪", "right hook"),
        ("⤴", "arrow curving up"),
        ("⤵", "arrow curving down"),
        ("↖", "up left arrow"),
        ("↗", "up right arrow"),
        ("↘", "down right arrow"),
        ("↙", "down left arrow"),
        ("⟵", "long left arrow"),
        ("⟶", "long right arrow"),
        ("➜", "heavy round arrow"),
        ("➤", "arrowhead right"),
    ],
    "Tech & Legal": [
        ("©", "copyright"),
        ("®", "registered trademark"),
        ("™", "trademark"),
        ("℠", "service mark"),
        ("⌘", "command mac"),
        ("⌥", "option alt mac"),
        ("⇧", "shift key"),
        ("⌃", "control key"),
        ("⌫", "backspace delete"),
        ("⏎", "return enter"),
        ("⎋", "escape"),
        ("⇥", "tab"),
        ("␣", "space"),
        ("⏻", "power"),
        ("✓", "check mark"),
        ("✔", "heavy check mark"),
        ("✗", "ballot x"),
        ("✘", "heavy ballot x"),
        ("★", "black star"),
        ("☆", "white star"),
        ("♠", "spade"),
        ("♣", "club"),
        ("♥", "heart card"),
        ("♦", "diamond card"),
        ("♪", "eighth note music"),
        ("♫", "beamed notes music"),
        ("☮", "peace"),
        ("☯", "yin yang"),
        ("☢", "radioactive"),
        ("☣", "biohazard"),
        ("♾", "infinity permanent"),
    ],
    "Greek": [
        ("α", "alpha"),
        ("β", "beta"),
        ("γ", "gamma"),
        ("δ", "delta"),
        ("ε", "epsilon"),
        ("ζ", "zeta"),
        ("η", "eta"),
        ("θ", "theta"),
        ("λ", "lambda"),
        ("μ", "mu"),
        ("ν", "nu"),
        ("ξ", "xi"),
        ("π", "pi"),
        ("ρ", "rho"),
        ("σ", "sigma"),
        ("τ", "tau"),
        ("φ", "phi"),
        ("χ", "chi"),
        ("ψ", "psi"),
        ("ω", "omega"),
        ("Γ", "capital gamma"),
        ("Δ", "capital delta"),
        ("Θ", "capital theta"),
        ("Λ", "capital lambda"),
        ("Ξ", "capital xi"),
        ("Π", "capital pi"),
        ("Σ", "capital sigma"),
        ("Φ", "capital phi"),
        ("Ψ", "capital psi"),
        ("Ω", "capital omega ohm"),
    ],
}
